nav:
  - 简介: "index.md"
  - 用户指南: 
      安装运行: "user-guide/installation.md"
      "Docker 镜像构建指引": "user-guide/docker-image-specification.md"
  - 开发指南: 
      简介: "development-guide/index.md"
      后端架构: "development-guide/server-architecture.md"
      评测架构: "development-guide/grader-architecture.md"
      前端架构: "development-guide/frontend-architecture.md"

site_name: Autograder 使用文档
site_url: https://autograder-docs.howardlau.me/
repo_url: https://github.com/howardlau1999/autograder-docs
copyright: |
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  custom_dir: docs/overrides
  language: zh
  features:
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/weather-night
        name: 夜间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/weather-sunny
        name: 白天模式
plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      type: iso_datetime
      timezone: Asia/Shanghai
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - admonition
  - def_list
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/howardlau1999
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/howardlau1999
